Add 2-step admin setting
madfish-solutions/yupana-protocol-core pull request #87
Opened 2022-03-14 17:42 UTC by LikoIlya

2022-03-16 13:19 UTC, konchunas approved these changes

2022-03-16 13:33 UTC, konchunas requested changes

2022-03-16 13:33 UTC, konchunas commented on contracts/partial/yToken/adminMethods.ligo
> +        then s.admin := s.admin_candidate
You also need to reset `admin_candidate` to zero in any case

2022-03-17 17:32 UTC, LikoIlya commented on test/yToken.test.js
> +    // approve admin by candidate
```suggestion
    // stop approving admin by admin
```

2022-03-18 13:16 UTC, merged